### ISSUE TITLE
Mass DNS Querys

### ISSUE THREAD

**Issue by nstueber** [iobroker-community-adapters/ioBroker.synology#184]
Hello Developer, 

my pihole shows massive DNS Querys from IO-Broker. 

It seems that the Synology adapter wants to resolve the IP of the disk station several times per query. Stopping the adapter also stops the DNS querys. 

BR
Nico

**Comment by nstueber** [comment]
The Adapter generates over 4000 DNS Queries for the same address (Disk Station) in less than 15 minutes. I changed the settings how often the adapter should rescan the Diskstation this helps of course. Anyway, everytime the adapter refreshes the data more than 5 DNS querys are send for the same host within 1 second.

**Comment by Apollon77** [comment]
Then configure the IP instead of the name of your NAS? Then there will be no DNS lookups

**Comment by mcm1957** [comment]
Check the poll time. In my oppinion the poll time default (500ms) is too small (to many polls occure)
Per design the adapter issues several rest requests each causing a dns query (if I read the code correctly). So if dns queries are a issue, use a IP as Apollon already stated.

**Comment by mcm1957** [comment]
The adapter uses the base package htt.ps://github.com/kwent/syno. The datat retrieved from the synology nas is read by multiple rest requests. Those requests cause dns queries if the nas is addressed by name.

It's outside the scope of this adapter to cache dns returns. Please use the IP address instead of the domain name if possible. 

Currently no change ob behaviour is planned.
