### ISSUE TITLE
Every 3 sec there is a login on the DS

### ISSUE THREAD

**Issue by capitaenz** [iobroker-community-adapters/ioBroker.synology#284]
Hello,

I noticed today that every 3 sec there is a login on the DS.

Synology DS 920+ (DSM 7.2-64570 Update 1) with the loginproblems
ioBroker on the 2. DS 920+ (DSM 7.2-64570 Update 3) ioBroker on VMM
Node.js v16.19.0
jsController 4.0.24
Adapter 3.0.0
Adapter lights green and works.

`synology.2 2023-10-06 19:56:12.974 info DSM 7 detected, set all to true
synology.2 2023-10-06 19:56:12.973	info DSM 7
synology.2 2023-10-06 19:56:10.196	info Connecting to Synology 192.168.0.88:5001
synology.2 2023-10-06 19:56:10.153	info starting. Version 3.0.0 in /opt/iobroker/node_modules/iobroker.synology, node: v16.19.0, js-controller: 4.0.24
synology.2 2023-10-06 19:55:44.924 info Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
synology.2 2023-10-06 19:55:44.923 info terminating
synology.2 2023-10-06 19:55:44.912	info Got terminate signal TERMINATE_YOURSELF

06.10.2023 20:00:00 Warnung DS920_DuS iobroker Verbindung User [iobroker] from [192.168.0.117] failed to sign in to [DSM] via [password] due to authorization failure.
06.10.2023 19:59:56 Warnung DS920_DuS iobroker Verbindung User [iobroker] from [192.168.0.117] failed to sign in to [DSM] via [password] due to authorization failure.
06.10.2023 19:59:53 Warnung DS920_DuS iobroker Verbindung User [iobroker] from [192.168.0.117] failed to sign in to [DSM] via [password] due to authorization failure.
06.10.2023 19:59:50 Warnung DS920_DuS iobroker Verbindung User [iobroker] from [192.168.0.117] failed to sign in to [DSM] via [password] due to authorization failure.`

What can I do?
Many greetings
Leif

**Comment by mcm1957** [comment]
_06.10.2023 20:00:00 Warnung DS920_DuS iobroker Verbindung User [iobroker] from [192.168.0.117] failed to sign in to [DSM] via [password] due to authorization failure._

This looks like you have some authorization problem. Either user / password or 2FA are incorrect. In addition Synology might have blacklisted the iobroker system.

I suggest to discuss this problem at the forum (forum.iobroker.net) as there are more useres that could help and according to the current knowlegde no erro at the adapter is visible.

**Comment by capitaenz** [comment]
@mcm1957 
I'll try the forum, but why does the adapter still work and light green even though there are the alleged login problems?
